FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGlvcy1hcHAtYXBiCmRlc2NyaXB0aW9uOiBTZXRzIHVwIGFuIGlP\
UyBBcHAgcmVwcmVzZW50YXRpb24uCmJpbmRhYmxlOiBGYWxzZQphc3luYzogb3B0aW9uYWwKdGFn\
czogCiAgLSBtb2JpbGUKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IGlPUyBBcHAKICBjb25zb2xl\
Lm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZhIGZhLWFwcGxlCnBsYW5zOgogIC0gbmFtZTogZGVm\
YXVsdAogICAgZGVzY3JpcHRpb246IFNldHMgdXAgYW4gaU9TIEFwcCByZXByZXNlbnRhdGlvbi4K\
ICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFyYW1ldGVyczogCiAgICAtIG5h\
bWU6IGFwcE5hbWUKICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgZGVmYXVsdDogbXlhcHAKICAg\
ICAgdHlwZTogc3RyaW5nCiAgICAgIHRpdGxlOiB5b3VyIG5ldyBhcHBzIG5hbWUK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
