FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGlvcy1hcHAtYXBiCmRlc2NyaXB0aW9uOiBTZXRzIHVwIGFuIGlP\
UyBBcHAgcmVwcmVzZW50YXRpb24uCmJpbmRhYmxlOiBGYWxzZQphc3luYzogb3B0aW9uYWwKdGFn\
czogCiAgLSBtb2JpbGUKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IGlPUyBBcHAKICBjb25zb2xl\
Lm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZhIGZhLWFwcGxlCiAgaW1hZ2VVcmw6ICJpbWFnZXMv\
bG9nb3MvYXBwbGUucG5nIgogIGRvY3VtZW50YXRpb25Vcmw6ICJodHRwOi8vZG9jcy5hZXJvZ2Vh\
ci5vcmciCiAgc2VydmljZU5hbWU6IGlPUy1hcHAKcGxhbnM6CiAgLSBuYW1lOiBkZWZhdWx0CiAg\
ICBkZXNjcmlwdGlvbjogU2V0cyB1cCBhbiBpT1MgQXBwIHJlcHJlc2VudGF0aW9uLgogICAgZnJl\
ZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJzOiAKICAgIC0gbmFtZTogYXBw\
TmFtZQogICAgICByZXF1aXJlZDogVHJ1ZQogICAgICBkZWZhdWx0OiBteWFwcAogICAgICB0eXBl\
OiBzdHJpbmcKICAgICAgdGl0bGU6IEFwcGxpY2F0aW9uIE5hbWUKICAgIC0gbmFtZTogYXBwSWRl\
bnRpZmllcgogICAgICByZXF1aXJlZDogVHJ1ZQogICAgICB0eXBlOiBzdHJpbmcKICAgICAgdGl0\
bGU6IEJ1bmRsZSBJRA=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY mobile /usr/bin
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
